// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web.Api.Infrastructure.Data.EntityFramework;

namespace Web.Api.Infrastructure.Migrations
{
    [DbContext(typeof(AppicationDbContext))]
    [Migration("20200511223256_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Web.Api.Core.Entity.Cliente", b =>
                {
                    b.Property<decimal>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IdCliente")
                        .HasColumnType("numeric(18,0)")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(300)")
                        .HasMaxLength(300);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<decimal>("Identifiacion")
                        .HasColumnName("Identifiacion")
                        .HasColumnType("numeric(18,0)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("IdCliente");

                    b.ToTable("TEST_CLIENTE");
                });

            modelBuilder.Entity("Web.Api.Core.Entity.Factura", b =>
                {
                    b.Property<decimal>("IdFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IdFactura")
                        .HasColumnType("numeric(18,0)")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("FechaVenta")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("IdCliente")
                        .HasColumnName("IdCliente")
                        .HasColumnType("numeric(18,0)");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnName("ValorTotal")
                        .HasColumnType("numeric(18,3)");

                    b.HasKey("IdFactura");

                    b.HasIndex("IdCliente");

                    b.ToTable("TEST_FACTURA");
                });

            modelBuilder.Entity("Web.Api.Core.Entity.FacturaDetalle", b =>
                {
                    b.Property<decimal>("IdFacturaDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IdFacturaDetalle")
                        .HasColumnType("numeric(18,0)")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<decimal>("IdFactura")
                        .HasColumnName("IdFactura")
                        .HasColumnType("numeric(18,0)");

                    b.Property<decimal>("IdProducto")
                        .HasColumnName("IdProducto")
                        .HasColumnType("numeric(18,0)");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnName("ValorTotal")
                        .HasColumnType("numeric(18,3)");

                    b.Property<decimal>("ValorUnidad")
                        .HasColumnName("ValorUnidad")
                        .HasColumnType("numeric(18,3)");

                    b.HasKey("IdFacturaDetalle");

                    b.HasIndex("IdFactura");

                    b.HasIndex("IdProducto");

                    b.ToTable("TEST_FACTURA_DETALLE");
                });

            modelBuilder.Entity("Web.Api.Core.Entity.Producto", b =>
                {
                    b.Property<decimal>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IdProducto")
                        .HasColumnType("numeric(18,0)")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorUnidad")
                        .HasColumnName("ValorUnidad")
                        .HasColumnType("numeric(18,3)");

                    b.HasKey("IdProducto");

                    b.ToTable("TEST_PRODUCTO");
                });

            modelBuilder.Entity("Web.Api.Core.Entity.Factura", b =>
                {
                    b.HasOne("Web.Api.Core.Entity.Cliente", "ClienteEntity")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Web.Api.Core.Entity.FacturaDetalle", b =>
                {
                    b.HasOne("Web.Api.Core.Entity.Factura", "FacturaEntity")
                        .WithMany()
                        .HasForeignKey("IdFactura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web.Api.Core.Entity.Producto", "ProductoEntity")
                        .WithMany()
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
